### ISSUE TITLE
No folding for the json of the word has space at start of Line

### ISSUE THREAD

**Issue by OmarBoshra** [harianus/blog.adriaan.io#12]
![issuew](https://user-images.githubusercontent.com/47230931/62006104-804a0700-b13c-11e9-803e-4869c5203ee8.PNG)

The folding works if there is no space between the word at the start of the line.Else the folding doesn't show .please fix that.

**Comment by adriaanvanrossum** [comment]
Feel free so submit a PR

**Comment by adriaandotcom** [comment]
I think you're referring to this blog post https://blog.adriaan.io/sublime-pretty-json.html. I didn't write this plugin. I think you should report the bug in this repo https://github.com/dzhibas/SublimePrettyJson. I would also suggest to approach Nikolajus (@dzhibas) in a nice manner. He does provide this plugin for free.
