### ISSUE TITLE
Key Bindings Missing

### ISSUE THREAD

**Issue by RandallShanePhD** [harianus/blog.adriaan.io#16]
Great lib!

Installed it on Sublime Text 3.2.2 build 3211 on OSX Catalina 10.15.3 and I noted there were no key bindings in the package settings.  The package is there and I can modify settings but key bindings are missing.  I tried CMD + CRTL + j with no luck.  I think it simply isn't getting the command to run.  Have you seen this before?

Thanks man!

[R]

<img width="831" alt="Screen Shot 2020-02-26 at 4 46 06 PM" src="https://user-images.githubusercontent.com/6483047/75398656-844b2c80-58b7-11ea-8b02-f2b7734e1d69.png">

**Comment by RandallShanePhD** [comment]
nvm - I got it!!  The key binding specified works as long as it parses the JSON.  There's a margin between python dict & JSON.  Thats on me!  Thanks for the package - works great!!

**Comment by adriaandotcom** [comment]
Glad you found out ;)
